
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes_other
  "LCGReflex/StringMap",
  "LCGReflex/std::pair<pat::IsolationKeys,reco::IsoDeposit>",
  "LCGReflex/std::pair<std::basic_string<char>,std::vector<float> >",
  "LCGReflex/pat::CandKinResolution",
  "LCGReflex/std::vector<pat::CandKinResolution>",
  "LCGReflex/pat::LookupTableRecord",
  "LCGReflex/std::vector<pat::LookupTableRecord>",
  "LCGReflex/std::vector<std::pair<pat::IsolationKeys,reco::IsoDeposit> >",
  "LCGReflex/pat::EventHypothesis",
  "LCGReflex/std::vector<pat::EventHypothesis>",
  "LCGReflex/pat::VertexAssociation",
  "LCGReflex/std::vector<pat::VertexAssociation>",
  "LCGReflex/pat::TauJetCorrFactors",
  "LCGReflex/std::vector<pat::TauJetCorrFactors>",
  "LCGReflex/pat::JetCorrFactors",
  "LCGReflex/std::vector<pat::JetCorrFactors>",
  "LCGReflex/edm::ValueMap<pat::LookupTableRecord>",
  "LCGReflex/edm::Wrapper<edm::ValueMap<pat::LookupTableRecord> >",
  "LCGReflex/edm::Wrapper<std::vector<pat::EventHypothesis> >",
  "LCGReflex/edm::ValueMap<pat::VertexAssociation>",
  "LCGReflex/edm::Wrapper<edm::ValueMap<pat::VertexAssociation> >",
  "LCGReflex/edm::Wrapper<StringMap>",
  "LCGReflex/edm::ValueMap<pat::TauJetCorrFactors>",
  "LCGReflex/edm::Wrapper<edm::ValueMap<pat::TauJetCorrFactors> >",
  "LCGReflex/edm::ValueMap<pat::JetCorrFactors>",
  "LCGReflex/edm::Wrapper<edm::ValueMap<pat::JetCorrFactors> >",
  "LCGReflex/edm::Wrapper<std::pair<std::basic_string<char>,std::vector<float> > >",
  "LCGReflex/edm::ValueMap<pat::CandKinResolution>",
  "LCGReflex/std::vector<std::pair<std::basic_string<char>,std::vector<float> > >",
  "LCGReflex/edm::Wrapper<edm::ValueMap<pat::CandKinResolution> >",
  "LCGReflex/edm::Wrapper<std::vector<std::pair<std::basic_string<char>,std::vector<float> > > >",
//--End   classes_other
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

