
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes_user
  "LCGReflex/pat::UserData",
  "LCGReflex/edm::Ptr<pat::UserData>",
  "LCGReflex/std::vector<edm::Ptr<pat::UserData> >",
  "LCGReflex/std::vector<pat::UserData*>",
  "LCGReflex/edm::ValueMap<edm::Ptr<pat::UserData> >",
  "LCGReflex/edm::Wrapper<edm::ValueMap<edm::Ptr<pat::UserData> > >",
  "LCGReflex/pat::UserHolder<reco::Vertex>",
  "LCGReflex/pat::UserHolder<reco::Track>",
  "LCGReflex/pat::UserHolder<ROOT::Math::SVector<double,5> >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SVector<double,4> >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SVector<double,3> >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SVector<double,2> >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SMatrix<double,5,5,ROOT::Math::MatRepSym<double,5> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SMatrix<double,4,4,ROOT::Math::MatRepSym<double,4> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SMatrix<double,3,3,ROOT::Math::MatRepSym<double,3> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::SMatrix<double,2,2,ROOT::Math::MatRepSym<double,2> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<double> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >",
  "LCGReflex/pat::UserHolder<ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag> >",
  "LCGReflex/pat::UserHolder<ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag> >",
  "LCGReflex/edm::OwnVector<pat::UserData,edm::ClonePolicy<pat::UserData> >",
  "LCGReflex/edm::Wrapper<edm::OwnVector<pat::UserData,edm::ClonePolicy<pat::UserData> > >",
//--End   classes_user
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

